//Actions constants
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN";

export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const RESET_SIGNUP_ERROR = "RESET_SIGNUP_ERROR";
export const NETWORK_FAILED = "NETWORK_FAILED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS";
export const USER_SIGN_OUT_ERROR = "USER_SIGN_OUT_ERROR";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const CLEAR_SIGNUP_ERROR = "CLEAR_SIGNUP_ERROR";

export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_ERROR = "GET_USER_DETAIL_ERROR";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const ADD_USER_DETAILS_SUCCESS = "ADD_USER_DETAILS_SUCCESS";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const RESET_PASSWORD_UPDATE = "RESET_PASSWORD_UPDATE";
export const RESET_USER_DATA_ERROR = "RESET_USER_DATA_ERROR";

export const ALERT_CANCEL_SUCCESS = "ALERT_CANCEL_SUCCESS";
export const ALERT_CANCEL_ERROR = "ALERT_CANCEL_ERROR";
export const RESET_CANCEL_ALERT = "RESET_CANCEL_ALERT";

export const GET_ALERT_SUCCESS = "GET_ALERT_SUCCESS";
export const GET_ALERT_ERROR = "GET_ALERT_ERROR";

export const EDIT_ALERT_SUCCESS = "EDIT_ALERT_SUCCESS";
export const EDIT_ALERT_ERROR = "EDIT_ALERT_ERROR";

export const DISBALE_DEVICE_SUCCESS = "DISBALE_DEVICE_SUCCESS";
export const DISBALE_DEVICE_ERROR = "DISBALE_DEVICE_ERROR";
export const RESET_NOTIFICATION_FLAG = "RESET_NOTIFICATION_FLAG";

export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";
export const RESET_NOTIF_DATA = "RESET_NOTIF_DATA";
export const SET_BADGE_COUNT = "SET_BADGE_COUNT";
export const RESET_BADGE_COUNT = "RESET_BADGE_COUNT";

export const UPDATE_NOTIFICATIONS_SETTINGS = "UPDATE_NOTIFICATIONS_SETTINGS";
export const UPDATE_NOTIFICATIONS_SETTINGS_SUCCESS =
  "UPDATE_NOTIFICATIONS_SETTINGS_SUCCESS";
export const UPDATE_NOTIFICATIONS_SETTINGS_ERROR =
  "UPDATE_NOTIFICATIONS_SETTINGS_ERROR";

export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ";
export const MARK_NOTIFICATION_AS_READ_SUCCESS =
  "MARK_NOTIFICATION_AS_READ_SUCCESS";
export const MARK_NOTIFICATION_AS_READ_ERROR =
  "MARK_NOTIFICATION_AS_READ_ERROR";

export const CREATE_ALERT_SUCCESS = "CREATE_ALERT_SUCCESS";
export const CREATE_ALERT_ERROR = "CREATE_ALERT_ERROR";
export const RESET_CREATE_ALERT_DATA = "RESET_CREATE_ALERT_DATA";

export const SESSION_EXPIRED = "SESSION_EXPIRED";
export const RESET_SESSION = "RESET_SESSION";
export const RESET_UPADTE_ALERT = "RESET_UPADTE_ALERT";

export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

//Calendar Action Constant
export const GET_AIRLINES_AVAILABILITY_SUCCESS =
  "GET_AIRLINES_AVAILABILITY_SUCCESS";
export const GET_AIRLINES_AVAILABILITY_ERROR =
  "GET_AIRLINES_AVAILABILITY_ERROR";

// Points deta
export const GET_AVAILABLE_CALENDAR_POINTS_SUCESS = "GET_AVAILABLE_CALENDAR_POINTS_SUCESS";
export const GET_AVAILABLE_CALENDAR_POINTS_ERROR = "GET_AVAILABLE_CALENDAR_POINTS_ERROR";

//Find Flight action
export const GET_AIRLINES_MEMBERSHIP_SUCCESS =
  "GET_AIRLINES_MEMBERSHIP_SUCCESS";
export const GET_AIRLINES_MEMBERSHIP_ERROR = "GET_AIRLINES_MEMBERSHIP_ERROR";

export const GET_POSSIBLE_ROUTES_SUCCESS = "GET_POSSIBLE_ROUTES_SUCCESS";
export const GET_POSSIBLE_ROUTES_ERROR = "GET_POSSIBLE_ROUTES_ERROR";

export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR";

export const GET_FLIGHT_SCHEDULE_SUCCESS = "GET_FLIGHT_SCHEDULE_SUCCESS";
export const GET_FLIGHT_SCHEDULE_ERROR = "GET_FLIGHT_SCHEDULE_ERROR";

export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_ERROR = "GET_PLANS_ERROR";
export const GET_NEAREST_AIRPORT_SUCCESS = "GET_NEAREST_AIRPORT_SUCCESS";

export const SEND_AUDIT_DATA_SUCCESS = "SEND_AUDIT_DATA_SUCCESS";
export const SEND_AUDIT_DATA_ERROR = "SEND_AUDIT_DATA_ERROR";

//Map Search action
export const GET_AVAILABLE_DESTINATIONS_SUCCESS =
  "GET_AVAILABLE_DESTINATIONS_SUCCESS";
export const GET_AVAILABLE_DESTINATIONS_ERROR =
  "GET_AVAILABLE_DESTINATIONS_ERROR";
export const RESET_MAP_DATA = "RESET_MAP_DATA";

export const RESET_CALENDAR_DATA = "RESET_CALENDAR_DATA"

export const RESET_FINDFLIGHT_DATA = "RESET_FINDFLIGHT_DATA"
//Manage Contact Details
export const SET_PRIMARY_EMAIL_SUCCESS = "SET_PRIMARY_EMAIL_SUCCESS";
export const SET_PRIMARY_EMAIL_ERROR = "SET_PRIMARY_EMAIL_ERROR";

export const SECONDARY_VERIFICATION_SUCCESS = "SECONDARY_VERIFICATION_SUCCESS";
export const SECONDARY_VERIFICATION_ERROR = "SECONDARY_VERIFICATION_ERROR";

export const PRIMARY_VERIFICATION_SUCCESS = "PRIMARY_VERIFICATION_SUCCESS";
export const PRIMARY_VERIFICATION_ERROR = "PRIMARY_VERIFICATION_ERROR";

export const CREATE_ALTERNATE_EMAIL_SUCCESS = "CREATE_ALTERNATE_EMAIL_SUCCESS";
export const CREATE_ALTERNATE_EMAIL_ERROR = "CREATE_ALTERNATE_EMAIL_ERROR";

export const DELETE_EMAIL_SUCCESS = "DELETE_EMAIL_SUCCESS";
export const DELETE_EMAIL_ERROR = "DELETE_EMAIL_ERROR";

export const DELETE_NUMBER_SUCCESS = "DELETE_NUMBER_SUCCESS";
export const DELETE_NUMBER_ERROR = "DELETE_NUMBER_ERROR";

export const VERIFY_NUMBER_SUCCESS = "VERIFY_NUMBER_SUCCESS";
export const VERIFY_NUMBER_ERROR = "VERIFY_NUMBER_ERROR";

export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_ERROR = "RESEND_OTP_ERROR";

export const RESET_MANAGE_CONTACT = "RESET_MANAGE_CONTACT";


export const SET_SECONDARY_EAMIL_PRIMARY_SUCCESS = "SET_SECONDARY_EAMIL_PRIMARY_SUCCESS"
export const SET_SECONDARY_EAMIL_PRIMARY_ERROR = "SET_SECONDARY_EAMIL_PRIMARY_ERROR"



export const GET_ALERT_NOTIFICATIONS = "GET_ALERT_NOTIFICATIONS";
export const GET_ALERT_NOTIFICATIONS_SUCCESS =
  "GET_ALERT_NOTIFICATIONS_SUCCESS";
export const GET_ALERT_NOTIFICATIONS_ERROR = "GET_ALERT_NOTIFICATIONS_ERROR";
export const RESET_ALERT_NOTIFICATION_STATUS =
  "RESET_ALERT_NOTIFICATION_STATUS";

export const GET_NOTIFICATIONS_DETAILS = "GET_NOTIFICATIONS_DETAILS";
export const GET_NOTIFICATIONS_DETAILS_SUCCESS =
  "GET_NOTIFICATIONS_DETAILS_SUCCESS";
export const GET_NOTIFICATIONS_DETAILS_ERROR =
  "GET_NOTIFICATIONS_DETAILS_ERROR";
export const RESET_NOTIFICATIONS_DETAILS = "RESET_NOTIFICATIONS_DETAILS";

//Geography

export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS";
export const GET_COUNTRY_LIST_ERROR = "GET_COUNTRY_LIST_ERROR";

export const GET_STATE_LIST = "GET_STATE_LIST";
export const GET_STATE_LIST_SUCCESS = "GET_STATE_LIST_SUCCESS";
export const GET_STATE_LIST_ERROR = "GET_STATE_LIST_ERROR";

export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_CITY_LIST_SUCCESS = "GET_CITY_LIST_SUCCESS";
export const GET_CITY_LIST_ERROR = "GET_CITY_LIST_ERROR";

export const GET_MAP_KEY = "GET_MAP_KEY";
export const GET_MAP_KEY_SUCCESS = "GET_MAP_KEY_SUCCESS";
export const GET_MAP_KEY_ERROR = "GET_MAP_KEY_ERROR";


export const GET_PEAK_OFFPEAK = "GET_PEAK_OFFPEAK";
export const GET_PEAK_OFFPEAK_SUCCESS = "GET_PEAK_OFFPEAK_SUCCESS";
export const GET_PEAK_OFFPEAK_ERROR = "GET_PEAK_OFFPEAK_ERROR";


export const ADD_MANAGE_CONTACT_DETAILS = "ADD_MANAGE_CONTACT_DETAILS"
export const ADD_MANAGE_CONTACT_DETAILS_SUCCESS = "ADD_MANAGE_CONTACT_DETAILS_SUCCESS"
export const ADD_MANAGE_CONTACT_DETAILS_ERROR = "ADD_MANAGE_CONTACT_DETAILS_ERROR"

export const UPDATE_AIRLINE_TIER = "UPDATE_AIRLINE_TIER"
export const UPDATE_AIRLINE_TIER_SUCCESS = "UPDATE_AIRLINE_TIER_SUCCESS"
export const UPDATE_AIRLINE_TIER_ERROR = "UPDATE_AIRLINE_TIER_ERROR"


export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS"
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR"
export const PROFILE_UPDATE = "PROFILE_UPDATE"


export const GET_MULTIPLE_SCHEDULE_DATA = "GET_MULTIPLE_SCHEDULE_DATA"
export const GET_MULTIPLE_SCHEDULE_DATA_ERROR = "GET_MULTIPLE_SCHEDULE_DATA_ERROR"
export const GET_MULTIPLE_SCHEDULE_DATA_SUCCESS = "GET_MULTIPLE_SCHEDULE_DATA_SUCCESS"


export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT"
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS"
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_SUCCESS"



export const GUEST_USER_POSTHOG = "GUEST_USER_POSTHOG"
export const GUEST_USER_POSTHOG_SUCCESS = "GUEST_USER_POSTHOG_SUCCESS"
export const GUEST_USER_POSTHOG_FAIL = "GUEST_USER_POSTHOG_FAIL"


export const LOGGEDIN_USER_POSTHOG = "LOGGEDIN_USER_POSTHOG"
export const LOGGEDIN_USER_POSTHOG_SUCCESS = "LOGGEDIN_USER_POSTHOG_SUCCESS"
export const LOGGEDIN_USER_POSTHOG_FAIL = "LOGGEDIN_USER_POSTHOG_FAIL"


export const USER_CONFIG_DETAILS = "USER_CONFIG_DETAILS"
export const USER_CONFIG_DETAILS_SUCCESS = "USER_CONFIG_DETAILS_SUCCESS"
export const USER_CONFIG_DETAILS_FAIL = "USER_CONFIG_DETAILS_FAIL"



export const GET_CABIN_CLASS = "LOGGEDIN_USER_POSTHOG"
export const GET_CABIN_CLASS_SUCCESS = "GET_CABIN_CLASS_SUCCESS"
export const GET_CABIN_CLASS_FAIL = "GET_CABIN_CLASS_FAIL"

export const GET_ZENDESK_CATEGORY = "GET_ZENDESK_CATEGORY"
export const GET_ZENDESK_CATEGORY_SUCCESS = "GET_ZENDESK_CATEGORY_SUCCESS"
export const GET_ZENDESK_CATEGORY_FAIL = "GET_ZENDESK_CATEGORY_FAIL"

export const POST_ZENDESK_TICKET = "POST_ZENDESK_TICKET"
export const POST_ZENDESK_TICKET_SUCCESS = "POST_ZENDESK_TICKET_SUCCESS"
export const POST_ZENDESK_TICKET_FAIL = "POST_ZENDESK_TICKET_FAIL"


export const CHECK_SEATS_AVAILABLE = "CHECK_SEATS_AVAILABLE"
export const CHECK_SEATS_AVAILABLE_SUCCESS = "CHECK_SEATS_AVAILABLE_SUCCESS"
export const CHECK_SEATS_AVAILABLE_FAIL = "CHECK_SEATS_AVAILABLE_FAIL"

